config/routes.rb
Rails.application.routes.draw do
  # 検索アクションへ
  get '/search' => 'search#search'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    get "search", to: "users#search"
    resource :follow
    resource :followings
    resource :followers

  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user




  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # コメントの追加、記事の削除と同時に削除する
	has_many :post_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
  
  # いいねしたかの判定
  
  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @user_today_books = Book.where(user_id: current_user.id).where(created_at: Time.zone.now.all_day)
    @user_1day_books = Book.where(user_id: current_user.id).where(created_at: 1.day.ago.all_day)
    @user_2day_books = Book.where(user_id: current_user.id).where(created_at: 2.day.ago.all_day)
    @user_3day_books = Book.where(user_id: current_user.id).where(created_at: 3.day.ago.all_day)
    @user_4day_books = Book.where(user_id: current_user.id).where(created_at: 4.day.ago.all_day)
    @user_5day_books = Book.where(user_id: current_user.id).where(created_at: 5.day.ago.all_day)
    @user_6day_books = Book.where(user_id: current_user.id).where(created_at: 6.day.ago.all_day)

    
    @book = Book.new

    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day

    @user_thisweek = Book.where(user_id: current_user.id).where(created_at: from...to)
    @user_lastweek = Book.where(user_id: current_user.id).where(created_at: (from - 6.day)...(to - 6.day))
    
    
    @date1 = Date.current.strftime('%d日')
    @date2 = Date.current.ago(1.days).strftime('%d日')
    @date3 = Date.current.ago(2.days).strftime('%d日')
    @date4 = Date.current.ago(3.days).strftime('%d日')
    @date5 = Date.current.ago(4.days).strftime('%d日')
    @date6 = Date.current.ago(5.days).strftime('%d日')
    @date7 = Date.current.ago(6.days).strftime('%d日')
    
    @year = Date.current.strftime('%Y年''%m月')
    
    
    
    @articles = @user_thisweek

    @article_by_day = @articles.group_by_day(:created_at).size
    # groupdateのgroup_by_dayメソッドで投稿日(created_at)に基づくグルーピングして個数計上。 
    # => {Wed, 05 May 2021=>23, Thu, 06 May 2021=>20, Fri, 07 May 2021=>3, Sat, 08 May 2021=>0, Sun, 09 May 2021=>12, Mon, 10 May 2021=>2}

    @chartlabels = @article_by_day.map(&:first).to_json.html_safe
    # 投稿日付の配列を格納。文字列を含んでいると正しく表示されないので.to_json.html_safeでjsonに変換。
    # => "[\"2021-05-05\",\"2021-05-06\",\"2021-05-07\",\"2021-05-08\",\"2021-05-09\",\"2021-05-10\"]"

    @chartdatas = @article_by_day.map(&:second)
    # 日別投稿数の配列を格納。
    # => [23, 20, 3, 0, 12, 2]
    

  end

  def index
    @users = User.all
    @book = Book.new
    @books = Book.all

  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"

    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end
  
  

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book_index.html.erb
 <table class="table table-bordered">
      <h2 style="font-weight: normal;">投稿数の前日比・前週比</h2>
        <thead>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= @user_today_books.count %>
            </td>
            <td>
              <%= @user_1day_books.count %>
            </td>
            <td>
              <% if @user_1day_books.count == 0 %>
                  前日までの投稿が0のため計測不可
              <% else %>
              　<% @day_before = @user_today_books.count / @user_1day_books.count.to_f  %>
              　<%= (@day_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>


      <table class="table table-bordered">
        <thead>
          <th>今週の投稿数</th>
          <th>先週の投稿数</th>
          <th>前週比</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @user_thisweek.count %></td>
            <td><%= @user_lastweek.count %></td>
            <td>
              <% if @user_lastweek.count == 0 %>
                  前週までの投稿が0のため計測不可
              <% else %>
                <% @week_before = @user_thisweek.count / @user_lastweek.count.to_f  %>
                <%= (@week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>


       <table class="table table-bordered">
      <h2 style="font-weight: normal;">直近7日間分の投稿数（表示:<%= @year %>）</h2>
        <thead>
          <th><%= @date7 %></th>
          <th><%= @date6 %></th>
          <th><%= @date5 %></th>
          <th><%= @date4 %></th>
          <th><%= @date3 %></th>
          <th><%= @date2 %></th>
          <th><%= @date1 %> 【本日】</th>
          <th>前週日</th>
        </thead>
        <tbody>
          <tr>
            <td><%= @user_6day_books.count %></td>
            <td><%= @user_5day_books.count %></td>
            <td><%= @user_4day_books.count %></td>
            <td><%= @user_3day_books.count %></td>
            <td><%= @user_2day_books.count %></td>
            <td><%= @user_1day_books.count %></td>
            <td><%= @user_today_books.count %></td>
            <td>
              <% if @user_lastweek.count == 0 %>
                  前週投稿無し<br>計測不可
              <% else %>
                <% @week_before = @user_thisweek.count / @user_lastweek.count.to_f  %>
                <%= (@week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
  <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        // # 'bar'でグラフタイプを縦棒グラフに指定
        type: 'line',
        data: {
          // # 横軸にとるデータ(今回は投稿日付)を埋め込む
          labels: ['<%= @date7 %>', '<%= @date6 %>', '<%= @date5 %>', '<%= @date4 %>', '<%= @date3 %>', '<%= @date2 %>', '<%= @date1 %>' ],
          datasets: [
            {
              label: '投稿数',
              // # 縦軸にとるデータ(今回は投稿数)を埋め込む
              data: [<%= @user_6day_books.count %>, <%= @user_5day_books.count %>, <%= @user_4day_books.count %>,<%= @user_3day_books.count %>,<%= @user_2day_books.count %>,<%= @user_1day_books.count %>,<%= @user_today_books.count %>],
              borderColor: 'rgba(255, 159, 64, 1)',
              backgroundColor: "rgba(0,0,0,0)"
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 10,
            suggestedMin: 0,
            stepSize: 1,
            callback: function(value, index, values){
              return  value +  '投稿'
            }
          }
        }]
      },

        }
      });
    });
  </script>
      <div class="row" style="margin-top: 25px;margin-left: 35%;">
<%= form_with url: user_search_path(@user), method: :get, remote: true do |f| %>
  <%= f.date_field :created_at %>
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>
</div>
  <%= render 'users/search',books: @books %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><!--自分の時はフォロできないようにする-->
      <% if user_signed_in? && current_user != user %>
      <!--すでにフォローされている場合には以下のように設定する-->
      <% if current_user.active_relationships.exists?(target_user_id: user.id) %>
      <!--ユーザー配列でidを取ってきてfollowのdeleteアクションを実行する-->
        <%= link_to 'フォローを外す', [user, :follow], method: :delete %>
      <% else %>
       <%= link_to 'フォローする', [user, :follow], method: :post%>
      <% end %>
      <% end %>
      </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        
      </tr>
    <% end %>
    
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
    <tr>
	  <th>follows</th>
	  <!--ユーザーのフォローの数を表示と覚えて記述を書いて、[user, :followings]へリンクしuser_idを貰ってfollowingsのshowへ行く-->
	  <th><%= link_to user.followings.count,  [user, :followings]%></th>
  </tr>
    <tr>
	  <th>followers</th>
	  <th><%= link_to  user.followers.count,  [user, :followers] %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/_search.html.erb
<div id="search_result">
  <% if @search_book.present? %>
    <h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book  %>
    </div>
    <div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'users/index',users: @users, books: @books %>



    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <!--自分の時はフォロできないようにする-->
      <% if user_signed_in? && current_user != @user %>
      <!--フォローできるように設定する-->
      <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
        <%= link_to 'unfollow', [@user, :follow], method: :delete %>
      <% else %>
       <%= link_to 'follow', [@user, :follow], method: :post%>
      <% end %>
      <% end %>


      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>

      <%= render 'books/index',books: @books %>

      <%= render 'users/book_index',books: @books %>

    </div>

  </div>
</div>