config/routes.rb
Rails.application.routes.draw do
  # 検索アクションへ
  get '/search' => 'search#search'
  devise_for :users

  root 'homes#top'
  get 'home/about' => 'homes#about'


  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :post_comments, only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    get "search", to: "users#search"
    resource :follow
    resource :followings
    resource :followers

  end



end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	# 多くの良いねを受け取る可能性がある、記事の削除と同時に削除する（いいね）
	has_many :favorites, dependent: :destroy
	# コメントの追加、記事の削除と同時に削除する
	has_many :post_comments, dependent: :destroy


	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_user = @book.user
    @post_comment = PostComment.new
    # 新着順で表示
    @post_comments = @book.post_comments.order(created_at: :desc)
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment_form.html.erb
<%= form_with model:[book,post_comment], remote: true do |f| %>
  <%= f.text_area :comment, size:"90x5" ,placeholder: "コメントをここに"%>
  <%= f.submit "送信する" %>
<% end %>

app/views/books/_comment_index.html.erb
<% book.post_comments.each do |post_comment| %>
   <tr>
    <td><%= attachment_image_tag(post_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg")  %><br>
    <%= link_to user_path(post_comment.user) do %>
    <%= post_comment.user.name %><br>
    <% end %>
    </td>
    <td><%= post_comment.comment %></td>
    
    <% if post_comment.user == current_user %>
    <td><%= link_to "削除", book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %></td>
    <% end %>
   </tr>
 <% end %>

app/views/books/_favorites.html.erb
<% if current_user.already_favorited?(book) %>
    <%= link_to  book_favorites_path(book),method: :delete, remote:true do %>
      <i class="far fa-thumbs-up"></i>
    <% end %>
<% else %>
    <%= link_to  book_favorites_path(book),method: :post, remote:true do%>
      <i class="far fa-thumbs-up"></i>
    <% end %>
<% end %>
   <%= book.favorites.count%>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
      <div class="vertical-scroll-table">
      <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
                    <% @books.each do |book| %>
                  <tbody>
                    <td><%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100'  %>
                    <% end %> </td>
                    <td><%= link_to book.title,book_path(book,title:book.title)%></td>
                    <td><%= book.body %></td>
                    <td>         
                    <% end %>
                 </tbody>
            </table>
            </div>
            

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
      <div class="error_explanation text-danger lead">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
      <ul><li>
        <%= message %>
        </li>
        </ul>
      <% end %>
    <% end %>
    </div>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'><h2>Books</h2>
      <div class="vertical-scroll-table">
      <table class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
                    <% @books.each do |book| %>
                  <tbody>
                    <td><%= link_to user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100'  %>
                    <% end %> </td>
                    <td><%= link_to book.title,book_path(book,title:book.title)%></td>
                    <td><%= book.body %></td>
                    <td>         
                    <div id="favorite-<%= book.id %>">
                      <%= render 'books/favorites', book: book %>
                    </div>
                    </td>
                    <td>
                    <%= link_to "#{ book.post_comments.count} コメント", book_path(book.id) %></td>
                    <% end %>
                 </tbody>
            </table>
            </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>

          <td>
            <!--↓非同期いいね-->
               <div id="favorite-<%= @book.id %>">
                  <%= render 'books/favorites', book: @book %>
               </div></td>
            <% if @book_user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>

            <td>
              <!--コメントの非同期通信-->
              <div class="comments">コメント件数：<%= @book.post_comments.count %></td>
　　　　　　　</div>
        </tr>
      </table>
            <table id="book_<%= @book.id %>" class="comments">
            <%= render 'books/comment_index',  book: @book  %>
            </table>
            <div>
            <%= render 'books/comment_form',  book: @book, post_comment: @post_comment%>
           <div>
    </div>
  </div>
</div>